add origin admin
silverorange/store pull request #157
Opened 2023-04-04 20:16 UTC by pparke

Adds a custom field that braintree can check in order to exempt admin orders from fraud protection

2023-04-17 23:52 UTC, gauthierm commented on Store/StoreBraintreePaymentProvider.php
> -			),
don't drop trailing comma

2023-04-17 23:54 UTC, gauthierm commented
The custom field set up in Braintree has the user-visible name `Origin Admin`. This is not really clear for humans. Consider a name like `Order Placed by Admin`

2023-04-17 23:58 UTC, gauthierm commented
I'm not sure if we need this field. See https://developer.paypal.com/braintree/docs/guides/premium-fraud-management-tools/server-side#skipping-premium-fraud-management-tools

If you're looking to configure CVV or AVS checks based on a custom field, I do not think that is possible.

2023-04-18 00:01 UTC, gauthierm requested changes
See PR feedback

2023-05-05 14:02 UTC, gauthierm commented
We already have an origin field on orders in the Rap package. If this approach is necessary, the existing flag should be used rather than adding a second flag.

2023-05-09 17:47 UTC, kendraSO commented
> I'm not sure if we need this field. See https://developer.paypal.com/braintree/docs/guides/premium-fraud-management-tools/server-side#skipping-premium-fraud-management-tools
> 
> If you're looking to configure CVV or AVS checks based on a custom field, I do not think that is possible.

I checked in with our contact at Braintree and they said `skipAdvancedFraudChecking` would work for what we're looking to do here. This does bypass their checks completely compared to the custom field that they would have to set to ignore on their side of things.

We had previously asked about [scaExemption](√https://developer.paypal.com/braintree/docs/reference/request/transaction/sale#sca_exemption) and that one does not skip their checks.

2025-07-25 19:54 UTC, closed without merging